name = "tech-updates"
account_id = ""
type = "javascript"
compatibility_date = "2024-04-07"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm install && pnpm run build"

[build.upload]
format = "modules"
main = "./worker.mjs"

[triggers]
crons = ["*/5 * * * *"]

[env.build.vars]
DATABASE_URL="" // Add your database url here
DIRECT_DATABASE_URL="" // Add your direct database url here
TELEGRAM_BOT_TOKEN="" // Add your telegram bot token here
TECHCRUNCH_API_URL="" // Add your techcrunch api url here
APPLICATION_ID="" // Add your application id here
PUBLIC_KEY="" // Add your public key here
DISCORD_BOT_TOKEN="" // Add your discord bot token here
DISCORD_WEBHOOK_URL="" // Add your discord webhook url here